types = ["japanese role playing game", "survival", "real time strategy", "shooter", "adventure", "action",
         "sim builder", "turn based strategy", "role playing game"]

game_data = [["real time strategy", "Total War: Warhammer III", "63", "T", "CREATIVE ASSEMBLY"],
             ["japanese role playing game", "Chrono Trigger", "86", "E", "Square Enix"],
             ["turn based strategy", "Sid Meier's Civilization VI", "83", "E", "Firaxis Games"],
             ["action", "Vampire Survivors", "98", "E", "poncle"],
             ["action", "Cult of the Lamb", "91", "T", "Massive Monster"],
             ["real time strategy", "Farthest Frontier", "85", "E", "Crate Entertainment"],
             ["sim builder", "Stardew Valley", "98", "E", "ConcernedApe"],
             ["adventure", "Stray", "97", "E", "Blue Twelve Studio"],
             ["casual", "The Sims 4", "87", "T", "Maxis"],
             ["sim builder", "Hardspace: Shipbreaker", "89", "E", "Blackbird Interactive"],
             ["shooter", "Tiny Tina's Wonderlands", "75", "T", "Gearbox Software"],
             ["action", "Assassin's Creed Odyssey", "89", "M", "Ubisoft Quebec"],
             ["adventure", "Return of the Obra Dinn", "96", "T", "Lucas Pope"],
             ["real time strategy", "Northgard", "88", "T", "Shiro Games"],
             ["action", "Elden Ring", "90", "M", "FromSoftware Inc"],
             ["survival", "V Rising", "88", "T", "Stunlock Studios"],
             ["shooter", "Resident Evil Village", "96", "M", "CAPCOM Co., Ltd."],
             ["sim builder", "Dorfromantik", "97", "E", "Toukana Interactive"],
             ["turn based strategy", "Darkest Dungeon", "91", "T", "Red Hook Studios"],
             ["real time strategy", "Total War: Warhammer II", "93", "T", "CREATIVE ASSEMBLY"],
             ["turn based strategy", "Warhammer 40,000: Chaos Gate", "77", "M", "Complex Games"],
             ["real time strategy", "Dune: Spice Wars", "81", "T", "Shiro Games"],
             ["sim builder", "Planet Coaster", "81", "E", "Frontier Developments"],
             ["sim builder", "RollerCoaster Tycoon 3", "84", "E", "Frontier Developments"],
             ["role playing game", "Disco Elysium", "94", "M", "ZA/UM"],
             ["action", "Nova Drift", "96", "E", "Chimeric"],
             ["real time strategy", "Total War: Warhammer", "78", "T", "CREATIVE ASSEMBLY"],
             ["role playing game", "Cypberpunk 2077", "77", "M", "CD PROJECT RED"],
             ["action", "Mount & Blade II: Bannerlord", "87", "T", "TaleWorlds Entertainment"],
             ["real time strategy", "Rome: Total War", "94", "T", "CREATIVE ASSEMBLY"],
             ["adventure", "Inscryption", "97", "E", "Daniel Mullins Games"],
             ["action", "Death Stranding", "93", "M", "KOJIMA PRODUCTIONS"],
             ["casual", "Garry's Mod", "96", "T", "Facepunch Studios"],
             ["turn based strategy", "Disciples III: Reincarnation", "69", "T", "Akella"],
             ["turn based strategy", "Crusader Kings II", "90", "T", "Paradox Development Studio"],
             ["role playing game", "Baldur's Gate: Enhanced Edition", "91", "T", "Beamdog"],
             ["adventure", "Shadowrun: Dragonfall - Director's Cut", "89", "T", "Harebrained Schemes"],
             ["adventure", "Shadowrun Returns", "88", "T", "Harebrained Schemes"],
             ["real time strategy", "Commandos 2: Men of Courage", "84", "T", "Pyro Studios"],
             ["action", "Deus Ex:Game of the Year Edition", "94", "M", "Ion Storm"],
             ["role playing game", "The Lord of the Rings Online", "81", "T", "Standing Stone Games, LLC"],
             ["role playing game", "Fallout 2", "94", "M", "Black Isle Studios"],
             ["role playing game", "Planescape: Torment: Enhanced Edition", "94", "M", "Beamdog"],
             ["turn based strategy", "Disciples II: Gallean's Return", "81", "T", "Strategy First"],
             ["turn based strategy", "Age of Wonders II: The Wizard's Throne", "82", "T", "Triumph Studios"],
             ["role playing game", "Baldur's Gate II: Enhanced Edition", "91", "T", "Beamdog"],
             ["role playing game", "Fallout", "94", "M", "Interplay Inc."],
             ["survival", "Ark: Survival Evolved", "83", "T", "Studio Wildcard"],
             ["sim builder", "Roller Coaster Tycoon 2", "88", "E", "Chris Sawyer Productions"],
             ["casual", "The Sims 3", "85", "T", "The Sims Studio"],
             ["casual", "Spore", "91", "E", "Maxis"],
             ["japanese role playing game", "Final Fantasy IX", "94", "T", "Square Enix"],
             ["japanese role playing game", "Final Fantasy VIII", "88", "T", "Square Enix"],
             ["japanese role playing game", "Final Fantasy VII", "92", "T", "Square Enix"],
             ["sim builder", "Sim City 4 Delux Edition", "79", "E", "EA - Maxis"]]